baseurl = "https://parsaiej.github.io"
title = "John Parsaie"
theme = ["hugo-coder"]
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "John Parsaie"
  info = "Sr. Staff Graphics Engineer @ Qualcomm Inc."
  description = "John Parsaie's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  colorScheme = "light"
  hidecolorschemetoggle = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/parsaiej"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/jparsaie/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Reel"
  weight = 2
  url = "reel/"